name: Smart Daily Dev Log

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update README
        run: |
          echo "" >> README.md
          echo "Updated at $(TZ='Asia/Manila' date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name "shemaiahezra-m"
          git config --global user.email "230293707+shemaiahezra-m@users.noreply.github.com"

          git add README.md
          git commit -m "docs: auto update" || echo "No changes"

          git push
